#!/bin/bash

# You can call this script like this:
# brightnessControl up
# brightnessControl down

# Script inspired by these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

case $1 in
  up)
    # increase the backlight by 5%
    light -A 5
    ;;
  down)
    # decrease the backlight by 5%
    light -U 5
    ;;
  digit)
    inotifywait -m -e close_write /sys/class/backlight/amdgpu_bl0/brightness |
      while read file; do
        brightness=$(tail /sys/class/backlight/amdgpu_bl0/brightness)
        brightness=$(echo "scale=2; ($brightness/255)*100" | bc -l | awk '{print substr($1, 1, length($1)-3)}')
        echo $brightness%
      done
    ;;
esac
