#!/bin/bash

# You can call this script like this:
# volumecontrol up
# volumecontrol down
# volumecontrol mute

function get_volume {
    pulsemixer --get-volume | awk '{print $1}'
}

function is_mute {
    pulsemixer --get-mute
}

function send_notification {
	volume=$(get_volume)
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
if [ "$volume" = "0" ]; then
        icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-muted.png"
notify-send -i "$icon_name" -r 5556 -u normal "$volume"
    else
	if [  "$volume" -lt "10" ]; then
	     icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-low.png"
notify-send -i "$icon_name" -r 5556 -u normal "$volume"
    else
        if [ "$volume" -lt "30" ]; then
            icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-low.png"
        else
            if [ "$volume" -lt "70" ]; then
                icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-medium.png"
            else
                icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-high.png"
            fi
        fi
    fi
fi

bar=$(seq -s "─" $(($volume/5)) | sed 's/[0-9]//g')
# Send the notification
notify-send -i "$icon_name" -r 5556 -u normal "$bar  $volume"
}

case $1 in
    up)
	# Set the volume on (if it was muted)
	pulsemixer --unmute> /dev/null
	# Up the volume (+ 2%)
	pulsemixer --change-volume +2 > /dev/null
	send_notification
	canberra-gtk-play -i audio-volume-change
	;;
    down)
	pulsemixer --unmute> /dev/null
	pulsemixer --change-volume -2 > /dev/null
	send_notification
	canberra-gtk-play -i audio-volume-change
	;;
    mute)
    	# Toggle mute
	pulsemixer --toggle-mute > /dev/null
	if is_mute ; then
    notify-send -i "/usr/share/icons/Adwaita/16x16/legacy/audio-volume-muted.png" -r 5556 -u normal "$bar Audio Muted"
	else
	    send_notification
	    canberra-gtk-play -i audio-volume-change
	fi
	;;
  digit)
    pactl subscribe | grep --line-buffered "sink" |
      while read -r line; do
        if [ $(is_mute) -eq "1" ]; then
          eww update volume-icon="󰝟"
          echo "M"
        else
          volume=$(get_volume)
          if [ $volume -eq "0" ]; then
            eww update volume-icon="󰝟"
          elif [ $volume -gt "0" ] && [ $volume -lt "20" ]; then
            eww update volume-icon=""
          elif [ $volume -gt "19" ] && [ $volume -lt "60" ]; then
            eww update volume-icon=""
          elif [ $volume -gt "59" ]; then
            eww update volume-icon=""
          fi
          echo $volume%
        fi
      done
  ;;
esac
